name: Fetch new plugins and Themes

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${GITHUB_WORKSPACE}/bin/requirements.txt
      - name: Fetch themes and plugins
        run: |
          python ${GITHUB_WORKSPACE}/bin/fetch_packages.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: z3by
      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add .
          git config --local user.email "zoaby.am@gmail.com"
          git config --local user.name "Ahmad Mostafa"
          git commit -m "AUTOMATED: fetch new vuepress themes and plugins" -a | exit 0
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
